events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/auth/ {
            rewrite ^/api/auth/(.*) /auth/$1 break;
            proxy_pass http://auth-service:3001;
        }

        location /api/users/ {
            rewrite ^/api/users/(.*) /users/$1 break;
            proxy_pass http://users-service:3002;
        }

        location /api/appointments/ {
            rewrite ^/api/appointments/(.*) /appointments/$1 break;
            proxy_pass http://appointments-service:3003;
        }
    }
}